In [2]:
import torch

In [8]:
# Создайте случайный FloatTensor размера 3x4x5
tensor = torch.rand(3, 4, 5)
tensor

tensor([[[0.8089, 0.5742, 0.5476, 0.2565, 0.4135],
         [0.8375, 0.5319, 0.7208, 0.6664, 0.5048],
         [0.8492, 0.7003, 0.5670, 0.2892, 0.2346],
         [0.0970, 0.0692, 0.5940, 0.3655, 0.1117]],

        [[0.2340, 0.1451, 0.7312, 0.0249, 0.4571],
         [0.7935, 0.5243, 0.6308, 0.0580, 0.6199],
         [0.8226, 0.3565, 0.2559, 0.0518, 0.5775],
         [0.8073, 0.9867, 0.0115, 0.0825, 0.3351]],

        [[0.7172, 0.0342, 0.2609, 0.1586, 0.1025],
         [0.4277, 0.8135, 0.3235, 0.0475, 0.5663],
         [0.5291, 0.3153, 0.6196, 0.9438, 0.0567],
         [0.4860, 0.9384, 0.0416, 0.2626, 0.1848]]])

In [9]:
# Выведите его форму (shape)
tensor.shape

torch.Size([3, 4, 5])

In [11]:
# Приведите его к форме 6 X 10
tensor = tensor.reshape(6, 10)
tensor

tensor([[0.8089, 0.5742, 0.5476, 0.2565, 0.4135, 0.8375, 0.5319, 0.7208, 0.6664,
         0.5048],
        [0.8492, 0.7003, 0.5670, 0.2892, 0.2346, 0.0970, 0.0692, 0.5940, 0.3655,
         0.1117],
        [0.2340, 0.1451, 0.7312, 0.0249, 0.4571, 0.7935, 0.5243, 0.6308, 0.0580,
         0.6199],
        [0.8226, 0.3565, 0.2559, 0.0518, 0.5775, 0.8073, 0.9867, 0.0115, 0.0825,
         0.3351],
        [0.7172, 0.0342, 0.2609, 0.1586, 0.1025, 0.4277, 0.8135, 0.3235, 0.0475,
         0.5663],
        [0.5291, 0.3153, 0.6196, 0.9438, 0.0567, 0.4860, 0.9384, 0.0416, 0.2626,
         0.1848]])

In [18]:
tensor * torch.LongTensor([1, 4, 2, 2, 1] * 2)

tensor([[0.8089, 2.2969, 1.0953, 0.5130, 0.4135, 0.8375, 2.1274, 1.4416, 1.3328,
         0.5048],
        [0.8492, 2.8011, 1.1340, 0.5783, 0.2346, 0.0970, 0.2767, 1.1879, 0.7311,
         0.1117],
        [0.2340, 0.5803, 1.4624, 0.0498, 0.4571, 0.7935, 2.0970, 1.2615, 0.1160,
         0.6199],
        [0.8226, 1.4261, 0.5119, 0.1036, 0.5775, 0.8073, 3.9466, 0.0229, 0.1650,
         0.3351],
        [0.7172, 0.1367, 0.5217, 0.3173, 0.1025, 0.4277, 3.2540, 0.6470, 0.0950,
         0.5663],
        [0.5291, 1.2613, 1.2393, 1.8877, 0.0567, 0.4860, 3.7534, 0.0831, 0.5251,
         0.1848]])

In [19]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
tensor = tensor * torch.LongTensor([1, 4, 2, 2, 1] * 2)

# Не удалось умножить тензор размера 6х10 на тензор размера 1х5, длины должны совпадать, поэтому я увеличил длину 
# второго тензора вдвое

In [22]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

print(tensor @ tensor.T)
print((tensor @ tensor.T).shape)

tensor([[16.9009, 12.1697, 10.7504, 14.2880, 10.2969, 14.9793],
        [12.1697, 12.2866,  5.9283,  6.8246,  3.6344,  8.0815],
        [10.7504,  5.9283,  9.7579, 11.2102,  9.4141, 11.3250],
        [14.2880,  6.8246, 11.2102, 19.6842, 14.5518, 18.4528],
        [10.2969,  3.6344,  9.4141, 14.5518, 12.4361, 14.4330],
        [14.9793,  8.0815, 11.3250, 18.4528, 14.4330, 21.6143]])
torch.Size([6, 6])


In [29]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
from torch.autograd import Variable

x = Variable(torch.tensor([1.]), requires_grad=True)
z = Variable(torch.tensor([0.5]), requires_grad=True)
t = Variable(torch.tensor([2.]), requires_grad=True)
y = x**3 + z - 75*t

In [32]:
y.backward([x, z, t])

In [36]:
print(f"""
    dy/dx = {x.grad};
    dy/dz = {z.grad};
    dy/dt = {t.grad}
""")


    dy/dx = tensor([3.]);
    dy/dz = tensor([1.]);
    dy/dt = tensor([-75.])



In [40]:
# Создайте единичный тензор размера 5x6
ones = torch.ones(5, 6)
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [41]:
# Переведите его в формат numpy
ones.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [81]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

In [82]:
from torch.optim import SGD

In [83]:
x = Variable(torch.tensor([1.]), requires_grad=True)
w = Variable(torch.tensor([1.]), requires_grad=True)
y = x**w - 2 * x**2 + 5
print(y)

tensor([4.], grad_fn=<AddBackward0>)


In [84]:
optimizer = SGD([x, w], lr=0.1)
y.backward()
optimizer.step()

In [95]:
y.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved variables after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved variables after calling backward.

In [91]:
x.grad, w.grad

(tensor([-3.]), tensor([0.]))